# Site settings
title: Julio Parra-Martinez
email:
description: > # this means to ignore newlines until "baseurl:" No description 
port: "4001"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julioparra.me" # the base hostname & protocol for your site
twitter_username:
github_username:  julioparra

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

plugins:
  - jekyll-bootstrap-sass
  - jekyll-octicons
